### ISSUE TITLE
October issue link is broken

### ISSUE THREAD

**Issue by jaidevd** [seg/2016-ml-contest#1]
In the README, there's a link to http://library.seg.org/toc/leedff/35/10 which says "The Leading Edge, volume 35, issue 10 was not found."

**Comment by kwinkunks** [comment]
Thanks Jaidev... I think because the publication date (1 Oct) was on a Saturday, the online edition may not be up till Monday. If it's still broken on Monday, we have a problem... I will check back. The manuscript is also [here in the repo for the tutorial](https://github.com/seg/tutorials-2016/blob/master/1610_Facies_classification/manuscript/facies_classification.md). Cheers!

**Comment by jaidevd** [comment]
👍

**Comment by kwinkunks** [comment]
Link is working today!
